/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import modelPath from "./blender/expoBooth.glb";

export function ExpoBooth(props) {
  const { nodes, materials } = useGLTF(modelPath);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ExpoBooth.geometry}
        material={materials["frame.001"]}
      />
    </group>
  );
}

useGLTF.preload(modelPath);
