/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import modelPath from "./blender/theatre.glb";
import DefaultMaterial from "../materials/DefaultMaterial";

export function Theatre(props) {
  const { nodes, materials } = useGLTF(modelPath);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.geo1.geometry}
        material={materials.Glass}
      >
        <meshStandardMaterial
          color={"cyan"}
          opacity={0.15} // set the opacity to control the level of transparency
          transparent // set the transparent property to true
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.geo1_1.geometry}
        material={materials.Frame}
      >
        <DefaultMaterial />
      </mesh>
    </group>
  );
}

useGLTF.preload(modelPath);