/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import modelPath from "./blender/waterRegion.glb";
import DefaultMaterial from "../materials/DefaultMaterial";
export function WaterRegion(props) {
  const { nodes, materials } = useGLTF(modelPath);
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.geo1.geometry}
          material={materials.grey}
        >
          <DefaultMaterial />
        </mesh>
        <mesh
          // castShadow
          receiveShadow
          geometry={nodes.geo1_1.geometry}
          material={materials.water}
        >
          {/* <meshStandardMaterial metalness={0.7} roughness={0.7} color={"white"}></meshStandardMaterial> */}
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload(modelPath);